# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- op: add
  path: /spec/template/spec/containers/-
  value:
    name: oauth-proxy
    image: openshift/oauth-proxy:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 1000
    ports:
      - name: public
        containerPort: 8443
    args:
      - --https-address=:8443
      - --provider=openshift
      - --skip-provider-button=true
      - --openshift-service-account=tekton-dashboard
      - --upstream=http://localhost:9097
      - --tls-cert=/etc/tls/private/tls.crt
      - --tls-key=/etc/tls/private/tls.key
      - --cookie-secret=SECRET
      - --skip-auth-regex=^/v1/extensions/.*\.js
    volumeMounts:
      - name: proxy-tls
        mountPath: /etc/tls/private
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: proxy-tls
    secret:
      secretName: proxy-tls
