---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: tekton-dashboard-build
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: tekton-dashboard
        app: tekton-dashboard
      name: tekton-dashboard
      namespace: tekton-pipelines
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: tekton-dashboard:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: https://github.com/tektoncd/dashboard.git
          ref: master
      triggers:
        - type: ConfigChange
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile
        type: Source
      successfulBuildsHistoryLimit: 5
    status:
      lastVersion: 0
