---
bases:
  - ../../base
images:
  - name: dashboardImage
    newName: gcr.io/tekton-nightly/dashboard
    newTag: latest
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../readonly/readonly-deployment-patch.yaml
