---
resources:
  - ../../base
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: tekton-dashboard-minimal
      namespace: tekton-pipelines
    path: cluster-role-patch-json.yaml
