---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: dashboardImage
    newName: github.com/tektoncd/dashboard/cmd/dashboard
    newTag:
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../readonly/readonly-deployment-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../dev/csrf-secure-cookie-patch.yaml
