---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  template:
    spec:
      containers:
        - name: tekton-dashboard
          env:
            - name: CSRF_SECURE_COOKIE
              value: "false"
