---
bases:
  - ../full-fat
images:
  - name: dashboardImage
    newName: github.com/tektoncd/dashboard/cmd/dashboard
    newTag:
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: csrf-secure-cookie-patch.yaml
