version: 2
updates:
  - package-ecosystem: "docker"
    directories:
    - "**/*"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
    - "area/dependency"
    - "dependencies"
    - "kind/misc"
    - "ok-to-test"
    - "docker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
    - "area/automation"
    - "dependencies"
    - "kind/misc"
    - "ok-to-test"
    - "github-actions"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
    - "area/dependency"
    - "dependencies"
    - "kind/misc"
    - "ok-to-test"
    - "go"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
    labels:
    - "area/dependency"
    - "dependencies"
    - "kind/misc"
    - "ok-to-test"
    - "javascript"
