# Documentation: https://golangci-lint.run/usage/configuration/

linters-settings:
  gomodguard:
    blocked:
      modules:
        - github.com/ghodss/yaml:
            recommendations:
              - sigs.k8s.io/yaml
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
          - pkg: github.com/ghodss/yaml
            desc: "use sigs.k8s.io/yaml instead, to be consistent"
linters:
  enable:
  - bodyclose
  - containedctx
  - decorder
  - dogsled
  - dupword
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - goconst
  - gocritic
  - gofmt
  - goimports
  - gomodguard
  - gosec
  - gosimple
  - govet
  - maintidx
  - makezero
  - misspell
  - musttag
  - nakedret
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nosprintfhostport
  - thelper
  - typecheck
  - unconvert
  - unused
  - usestdlibvars
  - whitespace
  disable:
  - contextcheck
  - cyclop
  - depguard
  - dupl
  - err113
  - exhaustruct
  - forcetypeassert
  - funlen
  - gci
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - gocyclo
  - godot
  - godox
  - gofumpt
  - gomoddirectives
  - iface
  - ireturn
  - lll
  - mirror
  - mnd
  - nestif
  - nlreturn
  - nonamedreturns
  - paralleltest
  - prealloc
  - predeclared
  - recvcheck
  - revive
  - staticcheck
  - stylecheck
  - tagliatelle
  - testpackage
  - tparallel
  - unparam
  - varnamelen
  - wastedassign
  - wrapcheck
  - wsl
  # Enabling presets means that new linters that we automatically adopt new
  # linters that augment a preset. This also opts us in for replacement linters
  # when a linter is deprecated.
  presets:
  - bugs
  - comment
  - complexity
  - error
  - format
  - import
  - metalinter
  - module
  - performance
  - sql
  - style
  - test
  - unused
issues:
  exclude-dirs:
  - vendor
  max-issues-per-linter: 0
  max-same-issues: 0
  include:
  # Enable off-by-default rules for revive requiring that all exported elements have a properly formatted comment.
  - EXC0012 # https://golangci-lint.run/usage/false-positives/#exc0012
  - EXC0014 # https://golangci-lint.run/usage/false-positives/#exc0014
  uniq-by-line: false
run:
  issues-exit-code: 1
  build-tags:
  - e2e
  timeout: 10m
  modules-download-mode: mod
