# Copyright 2019 The Tekton Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.13
USER root
WORKDIR /work
COPY . .
# CGO_ENABLED=1 is needed for -race on go test
RUN GO111MODULE=on CGO_ENABLED=1 NAMESPACE=default GOOS=linux go test -race -v ./...
