---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-dashboard
spec:
  workspaces:
    - name: source
  steps:
    - name: build-static
      image: node:14.18-alpine
      workingDir: $(workspaces.source.path)
      env:
        - name: CI
          value: "true"
      script: |
        #/usr/bin/env sh
        set -euxo pipefail

        npm ci
        npm run bootstrap:ci
        npm run build_ko
