---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-dashboard
spec:
  workspaces:
    - name: source
  steps:
    - name: build-static
      image: node:20.11-slim
      workingDir: $(workspaces.source.path)
      env:
        - name: CI
          value: "true"
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        npm ci
        npm run build
