# Copyright 2019-2024 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-dashboard
spec:
  workspaces:
    - name: source
  steps:
    - name: build-static
      image: docker.io/library/node:20.18.0-slim@sha256:ec35a66c9a0a275b027debde05247c081f8b2f0c43d7399d3a6ad5660cee2f6a
      workingDir: $(workspaces.source.path)
      env:
        - name: CI
          value: "true"
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        npm ci
        npm run build
