# Copyright 2021-2025 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: dashboard-prerelease-checks
spec:
  params:
  - name: package
    description: package to release
    default: github.com/tektoncd/dashboard
  - name: versionTag
    description: The X.Y.Z version that the artifacts would be tagged with
  - name: releaseBucket
    description: >-
      The bucket where to look for the release, in the format gs://<bucket-name>/<project-name>
  workspaces:
    - name: source-to-release
      description: The workspace where the repo has been cloned
  stepTemplate:
    env:
      - name: PACKAGE
        value: $(params.package)
      - name: VERSION_TAG
        value: $(params.versionTag)
      - name: RELEASE_BUCKET
        value: $(params.releaseBucket)
  steps:
    - name: check-git-tag
      image: ghcr.io/wolfi-dev/git:alpine@sha256:283fd0dcb7f0ff21a443a1a24ea908847672c0aa6b337a332d5f70d3637cd4a9
      script: |
        echo "Checking git tag"
        # Look for the tag in the list of tags
        git ls-remote --tags https://${PACKAGE} | \
          grep "${VERSION_TAG}$" || exit 0
        # If the version was found fail
        echo "Version ${VERSION_TAG} already tagged for ${PACKAGE}"
        exit 1
    - name: check-release-file
      image: gcr.io/google.com/cloudsdktool/cloud-sdk:523.0.1@sha256:59404471b06981074ab821230ced1cffa8be84799be5edadc60e2f8cf164fbfc
      script: |
        echo "Checking release file"
        # Check if the release file already exists
        # gsutil retuns 1 if the object was not found
        if gsutil stat ${RELEASE_BUCKET}/previous/${VERSION_TAG}/release.yaml; then
          echo "Release file already exists for ${VERSION_TAG} in the release bucket,"
          echo "but no git tag was found. To continue remove the release file first."
          exit 1
        fi
    - name: check-github-release
      image: docker.io/library/python:3.6-alpine3.9@sha256:f0b2142d5280c4e14162dce011b173c161cd7ccd1f562b6d97f6d14036954e2f
      script: |
        echo "Checking GitHub release"
        PACKAGE=$(echo ${PACKAGE} | cut -d/ -f2,3)
        # Check if the release exists on GitHub
        wget -q -O- --header 'Accept: application/vnd.github.v3+json' \
          https://api.github.com/repos/${PACKAGE}/releases | \
          python -c 'import sys; import json; print("\n".join([x["tag_name"] for x in json.load(sys.stdin)]))' | \
          grep "${VERSION_TAG}$" || exit 0
        echo "Release ${VERSION_TAG} already exists for ${PACKAGE}"
        exit 1
    - name: success-confirmation
      image: docker.io/library/alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d
      script: |
        echo "All pre-release checks for ${PACKAGE} @ ${VERSION_TAG} were successful"
        echo "Happy releasing 😺"
