---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: dashboard-release
spec:
  params:
  - name: package
    description: package to release
    default: github.com/tektoncd/dashboard
  - name: imageRegistry
    default: gcr.io/tekton-releases # REPLACE with your own registry
  - name: versionTag
    description: The X.Y.Z version that the artifacts should be tagged with
  resources:
  - name: source-repo
    type: git
  - name: bucket
    type: storage
  - name: builtDashboardImage
    type: image
  tasks:
    - name: build
      taskRef:
        name: build-tekton-dashboard
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: source
            resource: source-repo
    - name: publish-images
      runAfter: [build]
      taskRef:
        name: publish-tekton-dashboard
      params:
        - name: pathToProject
          value: $(params.package)
        - name: versionTag
          value: $(params.versionTag)
        - name: imageRegistry
          value: $(params.imageRegistry)
      resources:
        inputs:
          - name: source
            resource: source-repo
            from: [build]
          - name: bucket
            resource: bucket
        outputs:
          - name: bucket
            resource: bucket
          - name: builtDashboardImage
            resource: builtDashboardImage

