---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-dashboard-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/tektoncd/dashboard
    - name: revision
      value: v0.5.0
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-bucket-dashboard
spec:
  type: storage
  params:
    - name: type
      value: gcs
    - name: location
      # This value is where our folder sits, so for example
      # https://console.cloud.google.com/storage/browser/tekton-releases/dashboard
      value: gs://tekton-releases/dashboard
    - name: dir
      value: "y"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: dashboard-image
spec:
  type: image
  params:
    - name: url
      # Registry is provided via parameter, this is a hack see #569
      value: cmd/dashboard
