---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-dashboard-deployment-extension
  labels:
    rbac.dashboard.tekton.dev/aggregate-to-dashboard: "true"
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: dashboard.tekton.dev/v1alpha1
kind: Extension
metadata:
  name: sample-deployment-extension
  namespace: tekton-pipelines
spec:
  apiVersion: apps/v1
  name: deployments
  displayname: k8s deployments
