kind: Service
apiVersion: v1
metadata:
  name: dashboard-extension
  namespace: tekton-pipelines
  labels:
    app: sample-extension
    tekton-dashboard-extension: "true"
  annotations:
    tekton-dashboard-display-name: Sample
    tekton-dashboard-endpoints: "sample"  
    tekton-dashboard-bundle-location: "/bundle"
spec:
  type:
    NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: tekton-dashboard-extension