apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline0
spec:
  resources:
  - name: git-source
    type: git
  params:
  - name: pathToResourceFiles
    description: The path to the resource files to apply
    default: /workspace/git-source
  - name: apply-directory
    description: The directory from which resources are to be applied
    default: ""
  tasks:
  - name: pipeline0-task
    taskRef:
      name: pipeline0-task
    params:
    - name: pathToResourceFiles
      value: ${params.pathToResourceFiles}
    - name: apply-directory
      value: ${params.apply-directory}
    resources:
      inputs:
      - name: git-source
        resource: git-source
