---
resources:
  - ../../base
  - ../openshift-patches/route.yaml
  - ../openshift-patches/internal-dashboard-service.yaml
patches:
  - ../openshift-patches/dashboard-service.yaml
  - ../openshift-patches/serviceaccount.yaml
  - ../openshift-patches/oauth-proxy-in-deployment.yaml
images:
  - name: dashboardImage
    newName: github.com/tektoncd/dashboard/cmd/dashboard
    newTag:
