---
resources:
  - ../../base
  - ../openshift-patches/route.yaml
  - ../openshift-patches/internal-dashboard-service.yaml
patches:
  - ../openshift-patches/dashboard-service.yaml
  - ../openshift-patches/serviceaccount.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../readonly/readonly-deployment-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../dev/csrf-secure-cookie-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../openshift-patches/oauth-proxy-in-deployment.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../logout/deployment-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../openshift-patches/flags-deployment.yaml
images:
  - name: dashboardImage
    newName: github.com/tektoncd/dashboard/cmd/dashboard
    newTag:
namespace: openshift-pipelines
