---
resources:
  - ../../base
  - ../openshift-patches/route.yaml
  - ../openshift-patches/internal-dashboard-service.yaml
patches:
  - ../openshift-patches/dashboard-service.yaml
  - ../openshift-patches/serviceaccount.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../readonly/readonly-deployment-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../openshift-patches/oauth-proxy-in-deployment.yaml
images:
  - name: dashboardImage
    newName: gcr.io/tekton-nightly/dashboard
    newTag: latest
namespace: openshift-pipelines
