---
- op: add
  path: /spec/template/spec/containers/-
  value:
    name: oauth-proxy
    image: openshift/oauth-proxy:latest
    imagePullPolicy: IfNotPresent
    ports:
      - name: public
        containerPort: 8443
    args:
      - --https-address=:8443
      - --provider=openshift
      - --skip-provider-button=true
      - --openshift-service-account=tekton-dashboard
      - --upstream=http://localhost:9097
      - --tls-cert=/etc/tls/private/tls.crt
      - --tls-key=/etc/tls/private/tls.key
      - --cookie-secret=SECRET
      - --skip-auth-regex=^/v1/extensions/.*\.js
    volumeMounts:
      - name: proxy-tls
        mountPath: /etc/tls/private
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: proxy-tls
    secret:
      secretName: proxy-tls
