---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-dashboard
