---
resources:
  - ../full-fat
  - ./build.yaml
  - ../openshift-patches/route.yaml
  - ../openshift-patches/internal-dashboard-service.yaml
patches:
  - ../openshift-patches/dashboard-service.yaml
  - ../openshift-patches/serviceaccount.yaml
  - ../openshift-patches/oauth-proxy-in-deployment.yaml
  - ../dev/csrf-secure-cookie-patch.yaml
images:
  - name: dashboardImage
    newName: tekton-pipelines/tekton-dashboard
    newTag:
namespace: openshift-pipelines
