---
resources:
  - ../full-fat
  - ./build.yaml
  - ../openshift-patches/route.yaml
  - ../openshift-patches/internal-dashboard-service.yaml
patches:
  - ../openshift-patches/dashboard-service.yaml
  - ../openshift-patches/serviceaccount.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../dev/csrf-secure-cookie-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tekton-dashboard
      namespace: tekton-pipelines
    path: ../openshift-patches/oauth-proxy-in-deployment.yaml
images:
  - name: dashboardImage
    newName: tekton-pipelines/tekton-dashboard
    newTag:
namespace: openshift-pipelines
