name: Label Checker

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check kind labels
    runs-on: ubuntu-24.04
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: agilepathway/label-checker@c3d16ad512e7cea5961df85ff2486bb774caf3c5 # v1.6.65
        with:
          prefix_mode: true
          one_of: "kind/"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
