name: Slash Command Routing

permissions:
  contents: read

on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    if: ${{ github.event.issue.pull_request }}
    permissions:
      issues: write # for peter-evans/slash-command-dispatch to create issue reaction
      pull-requests: write # for peter-evans/slash-command-dispatch to create PR reaction
    uses: tektoncd/plumbing/.github/workflows/_slash.yml@cd41dc479fff3411a5ae8fb3cdca66f9c8ec7ab1 # main
    secrets:
      CHATOPS_TOKEN: ${{ secrets.CHATOPS_TOKEN }}
