apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: greeting
      default: Hello World
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "$(params.greeting)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Goodbye World!"
